### ISSUE TITLE
markets.bisq.network  is down

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq-markets#15]
@dan-da I just recognized that I get on a couple of API calls HTTP 500 back.  Could you please have a look what is going wrong? Thanks!

**Comment by ghost** [comment]
Same here.
After 1 or 2 minutes, I got this message:
Ouch! Encountered PHP Fatal Error. Shutting down. Array ( [type] => 1 [message] => Out of memory (allocated 35651584) (tried to allocate 69632 bytes) [file] => /tmp/bisq_opcache/27c2d17a21c53094ee50b7b45da3754e [line] => 121378 ) WARNING: ALERTS_MAIL_TO not defined in config. alert not sent with subject: [markets] [index.php] PHP Fatal Error! [pid: 23883]

**Comment by ManfredKarrer** [comment]
Fixed. Needed to upgrade VM to more RAM.
