### ISSUE TITLE
Currency List Outdated

### ISSUE THREAD

**Issue by aejontargaryen** [bisq-network/bisq-markets#16]
https://markets.bisq.network/api/ API uses/shows older version currency list.
Is there anything I can do to help correct this?

**Comment by sergeykrasilnik** [comment]
It now shows correct list but no trading info on all newly added assets.

**Comment by ghost** [comment]
@aejontargaryen 
I think that this issue is solved.
If yes, could you please close this issue.
Thanks.

**Comment by aejontargaryen** [comment]
Yes correct. Apologies
