### ISSUE TITLE
Not showing offers and trades with Dash as base currency

### ISSUE THREAD

**Issue by alexej996** [bisq-network/bisq-markets#4]
It seems like the website is not showing all offers on the Dash network.
I can see 2 DASH/EUR offers in my Bisq client that are not displayed on the website.

**Comment by cbeams** [comment]
Thanks, @alexej996. Paging @dan-da.

**Comment by dan-da** [comment]
busy just now.  I will take a look just as soon as I can.

**Comment by ManfredKarrer** [comment]
@dan-da 

The java apps need to be updated and built (master).

> cd exchange
> git pull
> mvn clean package -DskipTests

I killed all java processes and the sh script should make sure that they get restarted automatically.

Doge can be killed as it is not supported anymore.

**Comment by alexej996** [comment]
I will be closing this issue, since Dash is not supported anymore.
