### ISSUE TITLE
Bitcoin Clashic (BCH) not showing up in markets webapp

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq-markets#5]
Reported via https://twitter.com/clashicly/status/952502376723869696:

![image](https://user-images.githubusercontent.com/301810/34915480-d2a628cc-f927-11e7-9a6c-a6a5b49b7c13.png)

**Comment by ManfredKarrer** [comment]
@dan-da I updated and built latest master. so from the java side it should be in. Can u have a look?

**Comment by ManfredKarrer** [comment]
Market app is updated and all new altcoins are displayed.
