### ISSUE TITLE
Add payment method to trades endpoint in markets API

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq-markets#6]
@ripcurlx commented on [Wed Mar 07 2018](https://github.com/bisq-network/analytics/issues/6)

To make it easier to evaluate trades by payment methods it would be great to add this field to the trades API.

---

@cbeams commented on [Wed Mar 07 2018](https://github.com/bisq-network/analytics/issues/6#issuecomment-371184455)

This should probably go in https://github.com/bisq-network/markets, since that's where the work would actually be done.

**Comment by alfsbs** [comment]
I agree, this would be important to evaluate different payment methods.

**Comment by alfsbs** [comment]
Also, to include a BTC Amount endpoint would make it easier to compare, as in pairs such as XMR_BTC it is the XMR amount that is shown

**Comment by ManfredKarrer** [comment]
Implemented by https://github.com/bisq-network/bisq-markets/pull/11

**Comment by alfsbs** [comment]
It does not seem to work for PM, could you check? @dan-da does it also happen to you?

**Comment by ManfredKarrer** [comment]
@dan-da Could u have a look?

**Comment by dan-da** [comment]
deployed.  seems to be working.

**Comment by alfsbs** [comment]
Yess!! Thanx @dan-da ! This is really useful

**Comment by ghost** [comment]
If this issue is solved, maybe it could be closed.
Thanks.
-> @ripcurlx 

(btw, how is it that the stale/close bot didn't stale/close it ?)
