### ISSUE TITLE
Altcoins not showing up in API trades results

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/bisq-markets#8]
PPI, KOTO, SUEZ, RIN, WMCC, MAZA not showing up in API trades results

**Comment by fedegrc** [comment]
The API is not showing SEM trades:

https://markets.bisq.network/api/trades?market=all&limit=20&trade_id_from=5R9S1-b125f45c-004e-4da9-a1a4-6c9634f8b928-070&to=xbermboq-5b2c8943-a82e-4fc6-934b-cf499618bdb2-070

```
{ "market": "btc_gbp", "direction": "SELL", "price": "6329.50290000",  "amount": "0.06250000",
{ "market": "btc_usd", "direction": "SELL", "price": "8431.82140000",  "amount": "0.06500000",
{ "market": "btc_usd", "direction": "SELL", "price": "8454.91300000",  "amount": "0.06250000",
{ "market": "btc_cad", "direction": "BUY",  "price": "10716.89000000", "amount": "0.04760000",
{ "market": "xmr_btc", "direction": "BUY",  "price": "0.02362544",     "amount": "2.93327870",
{ "market": "btc_usd", "direction": "SELL", "price": "8446.99280000",  "amount": "0.05900000",
```

![screenshot_20180520_180404](https://user-images.githubusercontent.com/14953828/40283767-047a555e-5c5a-11e8-9aab-2e82689e8d90.png)

**Comment by cbeams** [comment]
Closing as fixed. SEM and all others should be showing up now with @ManfredKarrer's latest update to the markets app. See https://github.com/bisq-network/bisq-markets/issues/9#issuecomment-394184425.
