### ISSUE TITLE
Bitcore (BTX) not showing up in markets

### ISSUE THREAD

**Issue by dalijolijo** [bisq-network/bisq-markets#9]
![image](https://user-images.githubusercontent.com/37987466/40874862-82912ccc-6675-11e8-9c18-fbce6b4b0412.png)

BTX Bitcore is added to Bisq version 0.7.0. https://github.com/bisq-network/bisq-desktop/releases
But not showing up in the Currency Menue list at markets section on Bisq homepage.

**Comment by ManfredKarrer** [comment]
Market app is updated and all new altcoins are displayed.

**Comment by dalijolijo** [comment]
![image](https://user-images.githubusercontent.com/37987466/40890645-c162d0c2-6779-11e8-95f8-57d5de98d6ac.png)

Bitcore (BTX) is still not displayed.

**Comment by ManfredKarrer** [comment]
There are only currencies displayed which have trades or offers. BTX was probably never traded and there are no offer.
